/*
 * SPI.c
 *
 *  Created on: Apr 1, 2023
 *      Author: engdo
 */
#include "../00-LIB/Bit_Math.h"

#include "GIE.h"

#include "SPI_Interface.h"
#include "SPI_Private.h"
#include "SPI_Config.h"

static u8 Cpy_u8DataTransfer ;

/****************************************************************/
SPI_enuErrorStatus SPI_enuInit (void)
{
	SPI_enuErrorStatus LocalErrorStatus = SPI_enuOK;

	/*********** SPI EN/DS ****************/
	if (SPI_STATE == SPI_EN)
	{
		SET_BIT(SPI_SPCR,SPI_enuSPE);
	}
	else if (SPI_STATE == SPI_DS)
	{
		CLR_BIT(SPI_SPCR,SPI_enuSPE);
	}
	else
	{
		/* Do nothing */
	}

	/******* SPI INTERRUPT EN/DS ********/
	if (SPI_INTERRUPT_STATE == SPI_INTERRUPT_EN)
	{
		GIE_enuInit_EnableGIE();

		SET_BIT(SPI_SPCR,SPI_enuSPIE);
		SET_BIT(SPI_SPSR,SPI_enuSPIF);
	}
	else if (SPI_INTERRUPT_STATE == SPI_INTERRUPT_DS)
	{
		GIE_enuInit_DisbaleGIE();

		CLR_BIT(SPI_SPCR,SPI_enuSPIE);
		CLR_BIT(SPI_SPSR,SPI_enuSPIF);
	}
	else
	{
		/* Do nothing */
	}

	/******* Data Order Configuration *************/
	if (SPI_DATA_ORDER_CONFIG == SPI_DATA_ORDER_LSB)
	{
		SET_BIT(SPI_SPCR,SPI_enuDORD);
	}
	else if (SPI_DATA_ORDER_CONFIG == SPI_DATA_ORDER_MSB)
	{
		CLR_BIT(SPI_SPCR,SPI_enuDORD);
	}
	else
	{
		/* Do nothing */
	}

	/********** Master/Slave Select **************/
	if (SPI_MCU_MASTER_SLAVE_SELECT == SPI_MCU_SLAVE)
	{
		CLR_BIT(SPI_SPCR,SPI_enuMSTR);
	}
	else if (SPI_MCU_MASTER_SLAVE_SELECT == SPI_MCU_MASTER)
	{
		SET_BIT(SPI_SPCR,SPI_enuMSTR);
	}
	else
	{
		/* Do nothing */
	}

	/*********** SPI Clock Polarity *********************/
	if (SPI_POLARITY_SELECTION == SPI_POLARITY_LOW)
	{
		CLR_BIT(SPI_SPCR,SPI_enuCPOL);
	}
	else if (SPI_POLARITY_SELECTION == SPI_POLARITY_LOW)
	{
		SET_BIT(SPI_SPCR,SPI_enuCPOL);
	}
	else
	{
		/* Do nothing */
	}

	/********* SPI Clock Phase ******************/
	if (SPI_CLOCK_PHASE == SPI_DATA_SAMPLED_FIRST)
	{
		CLR_BIT(SPI_SPCR,SPI_enuCPHA);
	}
	else if (SPI_CLOCK_PHASE == SPI_DATA_SETUP_FIRST)
	{
		SET_BIT(SPI_SPCR,SPI_enuCPHA);
	}
	else
	{
		/* Do nothing */
	}

	/********* SPI Clock Rate Selection ************/
	switch (SPI_PRESCALER_SELECTION)
	{
	case SPI_enuPrescaler_4:
		CLR_BIT(SPI_SPCR,SPI_enuSPR0);
		CLR_BIT(SPI_SPCR,SPI_enuSPR1);
		CLR_BIT(SPI_SPSR,SPI_enuSPI2X);
		break;
	case SPI_enuPrescaler_16:
		SET_BIT(SPI_SPCR,SPI_enuSPR0);
		CLR_BIT(SPI_SPCR,SPI_enuSPR1);
		CLR_BIT(SPI_SPSR,SPI_enuSPI2X);
		break;
	case SPI_enuPrescaler_64:
		CLR_BIT(SPI_SPCR,SPI_enuSPR0);
		SET_BIT(SPI_SPCR,SPI_enuSPR1);
		CLR_BIT(SPI_SPSR,SPI_enuSPI2X);
		break;
	case SPI_enuPrescaler_128:
		SET_BIT(SPI_SPCR,SPI_enuSPR0);
		SET_BIT(SPI_SPCR,SPI_enuSPR1);
		CLR_BIT(SPI_SPSR,SPI_enuSPI2X);
		break;
	case SPI_enuPrescaler_2:
		CLR_BIT(SPI_SPCR,SPI_enuSPR0);
		CLR_BIT(SPI_SPCR,SPI_enuSPR1);
		SET_BIT(SPI_SPSR,SPI_enuSPI2X);
		break;
	case SPI_enuPrescaler_8:
		SET_BIT(SPI_SPCR,SPI_enuSPR0);
		CLR_BIT(SPI_SPCR,SPI_enuSPR1);
		SET_BIT(SPI_SPSR,SPI_enuSPI2X);
		break;
	case SPI_enuPrescaler_32:
		CLR_BIT(SPI_SPCR,SPI_enuSPR0);
		SET_BIT(SPI_SPCR,SPI_enuSPR1);
		SET_BIT(SPI_SPSR,SPI_enuSPI2X);
		break;
	case SPI_enuPrescaler_64_:
		SET_BIT(SPI_SPCR,SPI_enuSPR0);
		SET_BIT(SPI_SPCR,SPI_enuSPR1);
		SET_BIT(SPI_SPSR,SPI_enuSPI2X);
		break;
	}

	return LocalErrorStatus;
}
/****************************************************************/
SPI_enuErrorStatus SPI_enuMasterInit (void)
{
	SPI_enuErrorStatus LocalErrorStatus = SPI_enuOK;

	/* Data Order is left as default */

	/* NO Interrupt */
	GIE_enuInit_DisbaleGIE();

	CLR_BIT(SPI_SPCR,SPI_enuSPIE);
	CLR_BIT(SPI_SPSR,SPI_enuSPIF);

	/********** Master Select **************/
	SET_BIT(SPI_SPCR,SPI_enuMSTR);

	/* Leaving Both Clk polarity & Phase as defaults */

	/* Prescaler : Clk is Generated by the MASTER  : 16 */
	SET_BIT(SPI_SPCR,SPI_enuSPR0);
	CLR_BIT(SPI_SPCR,SPI_enuSPR1);
	CLR_BIT(SPI_SPSR,SPI_enuSPI2X);

	/* Enable SPI */
	SET_BIT(SPI_SPCR,SPI_enuSPE);

	return LocalErrorStatus;
}
/****************************************************************/
SPI_enuErrorStatus SPI_enuSlaveInit  (void)
{
	SPI_enuErrorStatus LocalErrorStatus = SPI_enuOK;

	/* Data Order is left as default */

	/* NO Interrupt */
	GIE_enuInit_DisbaleGIE();

	CLR_BIT(SPI_SPCR,SPI_enuSPIE);
	CLR_BIT(SPI_SPSR,SPI_enuSPIF);

	/********** Slave Select **************/
	CLR_BIT(SPI_SPCR,SPI_enuMSTR);

	/* Leaving Both Clk polarity & Phase as defaults */

	/* Enable SPI */
	SET_BIT(SPI_SPCR,SPI_enuSPE);

	return LocalErrorStatus;
}
/****************************************************************/
u8 SPI_u8Transcieve (u8 Cpy_u8Data)
{
	SPI_enuErrorStatus LocalErrorStatus = SPI_enuOK;

	u8 LocalCounter=0;
	u8 TIMEOUT = 255;

	u8 LocalInterruptFlag = GET_BIT(SPI_SPSR,SPI_enuSPIF);
	u8 LocalWriteCollisionFlag = GET_BIT(SPI_SPSR,SPI_enuWCOL);

	/********* Sending **********/
	SPI_SPDR = Cpy_u8Data;

	/* Waiting for transfer to complete */
	while ((LocalInterruptFlag != 1) && (LocalWriteCollisionFlag == 0) && (TIMEOUT > LocalCounter))
	{
		TIMEOUT --;
	}
	if (LocalWriteCollisionFlag == 1)
	{
		LocalErrorStatus = SPI_enuDataCollision;
	}

	/******** Receiving **********/
	/* Return the updated value in the register */
	return SPI_SPDR;

}
/****************************************************************/
/****************************************************************/
//SPI_enuErrorStatus SPI_enuSend (u8 Cpy_u8Data)
//{
//	SPI_enuErrorStatus LocalErrorStatus = SPI_enuOK;
//
//	u8 LocalInterruptFlag = GET_BIT(SPI_SPSR,SPI_enuSPIF);
//	u8 LocalWriteCollisionFlag = GET_BIT(SPI_SPSR,SPI_enuWCOL);
//
//	/* Check Interrupt Flag before sending */
//	while ((LocalInterruptFlag != 1) && (LocalWriteCollisionFlag == 0))
//	{
//		// Sending
//		Cpy_u8DataTransmission = Cpy_u8Data;
//	}
//	if (LocalWriteCollisionFlag == 1)
//	{
//		LocalErrorStatus = SPI_enuDataCollision;
//	}
//	// Raised when sending is done
//
//	return LocalErrorStatus;
//}
/****************************************************************/
//SPI_enuErrorStatus SPI_enuRead (u8 *Cpy_u8Data)
//{
//	SPI_enuErrorStatus LocalErrorStatus = SPI_enuOK;
//
//	u8 LocalInterruptFlag = GET_BIT(SPI_SPSR,SPI_enuSPIF);
//
//	/* Check Interrupt Flag before Recieving */
//	while (LocalInterruptFlag != 1)
//	{
//		// Receiving
//	}
//
//
//	return LocalErrorStatus;
//
//}
/****************************************************************/
SPI_ISR(SPI_INTERRUPT)
{
	SPI_SPDR = Cpy_u8DataTransfer;
}
