function RTW_SidParentMap() {
    this.sidParentMap = new Array();
    this.sidParentMap["GradingSystem:1"] = "GradingSystem";
    this.sidParentMap["GradingSystem:2"] = "GradingSystem";
    this.sidParentMap["GradingSystem:3"] = "GradingSystem";
    this.sidParentMap["GradingSystem:7"] = "GradingSystem";
    this.sidParentMap["GradingSystem:11"] = "GradingSystem";
    this.sidParentMap["GradingSystem:15"] = "GradingSystem";
    this.sidParentMap["GradingSystem:19"] = "GradingSystem";
    this.sidParentMap["GradingSystem:23"] = "GradingSystem";
    this.sidParentMap["GradingSystem:27"] = "GradingSystem";
    this.sidParentMap["GradingSystem:28"] = "GradingSystem";
    this.sidParentMap["GradingSystem:29"] = "GradingSystem";
    this.sidParentMap["GradingSystem:30"] = "GradingSystem";
    this.sidParentMap["GradingSystem:31"] = "GradingSystem";
    this.sidParentMap["GradingSystem:32"] = "GradingSystem";
    this.sidParentMap["GradingSystem:4"] = "GradingSystem:3";
    this.sidParentMap["GradingSystem:5"] = "GradingSystem:3";
    this.sidParentMap["GradingSystem:6"] = "GradingSystem:3";
    this.sidParentMap["GradingSystem:8"] = "GradingSystem:7";
    this.sidParentMap["GradingSystem:9"] = "GradingSystem:7";
    this.sidParentMap["GradingSystem:10"] = "GradingSystem:7";
    this.sidParentMap["GradingSystem:12"] = "GradingSystem:11";
    this.sidParentMap["GradingSystem:13"] = "GradingSystem:11";
    this.sidParentMap["GradingSystem:14"] = "GradingSystem:11";
    this.sidParentMap["GradingSystem:16"] = "GradingSystem:15";
    this.sidParentMap["GradingSystem:17"] = "GradingSystem:15";
    this.sidParentMap["GradingSystem:18"] = "GradingSystem:15";
    this.sidParentMap["GradingSystem:20"] = "GradingSystem:19";
    this.sidParentMap["GradingSystem:21"] = "GradingSystem:19";
    this.sidParentMap["GradingSystem:22"] = "GradingSystem:19";
    this.sidParentMap["GradingSystem:24"] = "GradingSystem:23";
    this.sidParentMap["GradingSystem:25"] = "GradingSystem:23";
    this.sidParentMap["GradingSystem:26"] = "GradingSystem:23";
    this.getParentSid = function(sid) { return this.sidParentMap[sid];}
}
    RTW_SidParentMap.instance = new RTW_SidParentMap();
